name: CI

on:
  push:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: master
          # Or pin a version:
          # version: 0.17.0-dev.1234+abcdef

      - name: Check formatting
        run: zig fmt --check .

      - name: Build project
        run: zig build

      # - name: Run tests
      #   run: zig build test
